name: Fetch GitHub Streak Image

on:
  schedule:
    - cron: '0 6 * * *' # daily at 6:00 UTC
  workflow_dispatch:

jobs:
  fetch-streak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download Streak Image
        run: |
          curl -o streak.png "https://streak-stats.demolab.com/?user=mdnurnabirana"

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add streak.png
          git commit -m "Update streak image" || echo "No changes"
          git push
